import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from '@/components/home'
import Service from '@/components/Service'
import Team from '@/components/Team'
import { Social,team,ProjectInfo,service } from '../typings'
import { fetchProjectInfo } from '../utils/fetchProjectInfo'
import { fetchService } from '../utils/fetchService'
import { fetchTeam } from '../utils/fetchTeam'
import { fetchSocials } from '../utils/fetchSocial'
import LoginSignup from '@/components/LoginSignup'

type Props={
  ProjectInfo:ProjectInfo;
  team:team[];
  service:service[];
  socials:Social[];

}
const inter = Inter({ subsets: ['latin'] })

const Home = ({ProjectInfo,team,service,socials}:Props) => {
  return (
    <div className='bg-[rgb(36,36,30)] text-white 
    h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0
    scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]'>
      <Head>
        <title>Hanut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header socials={socials}/>
      <section id='hero' className='snap-start'>
  <Hero ProjectInfo={ProjectInfo} />
</section>
<section id="home" className='snap-center'>
  <About projectInfo={ProjectInfo} />
</section>
<section id="team" className='snap-start'>
  <Team team={team}/>
</section>
<section id="service" className='snap-start'>
  <Service service={service}/>
</section>
<section id="loginsignup" className='snap-start'>
  <LoginSignup service={service}/>
</section>
</div>
  )
}
export default Home;


export const getStaticProps:GetStaticProps <Props>=async()=>{
  const ProjectInfo:ProjectInfo = await fetchProjectInfo();
  const team:team[] = await fetchTeam();
  const service:service[] = await fetchService();
  const socials:Social[]= await fetchSocials();
  

  return {
    props: {
      ProjectInfo,
      team,
      service,
      socials,
    },
    revalidate:10,
  }
} 